Repository binlab/terraform-aws-vault-ha-raft, pull requests merged in 2021-07, with the labels that each got.

#40 Common refactoring of codebase #1
  .pre-commit-config.yaml
  README.md
  alb.tf
  ami.tf
  debug.tf
  dlm.tf
  ec2.tf
  examples/route53-dns-records/route53.tf
  examples/vpc-peering-rds/main.tf
  examples/vpc-peering-rds/rds.tf
  examples/vpc-peering-rds/vpc.tf
  iam.tf
  ignition.tf
  kms.tf
  main.tf
  route53.tf
  security.tf
  tls.tf
  variables.tf
  vpc.tf
Labels: refactoring

#41 Update Vault version to latest (v1.7.3)
  README.md
  variables.tf
Labels: update

#42 Add output list of Internet public IPs (igw_public_ips)
  README.md
  outputs.tf
Labels: enhancement

#49 Fix deprecated rkt with switch to Docker
  README.md
  ignition.tf
  variables.tf
Labels: bug, critical

#50 Update docs for AMI changing on worked cluster
  README.md
  docs/change-ami-on-worked-cluster.md
  variables.tf
Labels: documentation

#52 Replace legacy Common Name field (CN) with SAN DNS
  tls.tf
Labels: bug, critical, depreciation

#53 Add Development and Debugging Sandbox
  .pre-commit-config.yaml
  README.md
  examples/development-debugging-sandbox/.gitignore
  examples/development-debugging-sandbox/README.md
  examples/development-debugging-sandbox/main.tf
  examples/development-debugging-sandbox/outputs.tf
  examples/development-debugging-sandbox/variables.tf
  locals.tf
  variables.tf
Labels: documentation, enhancement

#45 Add option to use external internet gateway
  README.md
  locals.tf
  variables.tf
  vpc.tf
Labels: bug

#55 Fix example of use external default VPC and IGW
  README.md
  examples/assign-default-vpc/.gitignore
  examples/assign-default-vpc/README.md
  examples/assign-default-vpc/main.tf
  examples/assign-default-vpc/outputs.tf
  examples/assign-default-vpc/variables.tf
  examples/assign-external-vpc/main.tf
Labels: documentation

#56 Bump Vault version to latest (v1.8.0)
  README.md
  variables.tf
Labels: update

#59 Fix dependency issue in case of VPC replacing
  vpc.tf
Labels: bug
